# Generated by Django 5.0.1 on 2024-01-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255, verbose_name="Адреса об'єкта")),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Широта в градусах')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Довгота в градусах')),
                ('relax', models.CharField(choices=[('parking', 'Парковка'), ('mangal', 'Мангал'), ('sauna', 'Сауна'), ('tenis', 'Теніс'), ('WI-FI', 'WI-FI')], max_length=300)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('highlighted_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Місце знаходження',
                'verbose_name_plural': 'Місця знаходження',
            },
        ),
    ]
